name: Build and Release Yak

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Build
      run: dotnet build --configuration Release

    - name: Check version consistency of git tag and CHANGELOG.md
      # needs in fsproj:
      # <Target Name="WriteChangelogVersion" AfterTargets="AfterBuild">
      #   <WriteLinesToFile File="bin/ChangelogVersion.txt" Lines="@(CurrentReleaseChangelog)" Overwrite="true" ContinueOnError="false" />
      # </Target>
      id: check_version
      shell: bash
      run: |
        CHANGELOG_VERSION=$(cat bin/ChangelogVersion.txt | tr -d '[:space:]')  
        if [ "${{ github.ref_name }}" != "$CHANGELOG_VERSION" ]; then
          echo "Version mismatch: git tag (${{ github.ref_name }}) and version in CHANGELOG.md ($CHANGELOG_VERSION) are not the same."
          exit 1
        fi

    # https://discourse.mcneel.com/t/github-action-to-yak/120815/3

    - name: Download Yak
      env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: curl -o bin\yak.exe http://files.mcneel.com/yak/tools/latest/yak.exe

    - name: Build Yak
      env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: ..\yak.exe build --platform win --version ${{ github.ref_name }}
      # I prepopulated a manifest file and copied it next to the .gha
      working-directory: bin/Release


    - name: Push new version to YAK
      run: ..\yak.exe push *.yak
      working-directory: bin/Release
      # You should create a secret using the token from here: yak.exe login --ci
      env:
        YAK_TOKEN: ${{ secrets.YAK_TOKEN }}

    # verify the package
    # "C:\Program Files\Rhino 8\System\Yak.exe" search fesh

